config/routes.rb
Rails.application.routes.draw do
  resources :spots
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'wods', to: "wods#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/explore', to: 'sessions#explore'
  get '/test-route', to: 'pages#test'
  get '/attributions', to: 'pages#attributions'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users#, except: 'index'

  resources :charges
  resources :sessions
  resources :sessions, module: "sessions" do
    resources :charges do
      get :success, to: 'charges#success'
    end
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: %i[ show edit update destroy ]

  # GET /spots or /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1 or /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots or /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully created." }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1 or /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully updated." }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1 or /spots/1.json
  def destroy
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url, notice: "Spot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spot_params
      params.require(:spot).permit(:name, :latitude, :longitude)
    end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_form.html.erb
<%= form_with(model: spot) do |form| %>
  <% if spot.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(spot.errors.count, "error") %> prohibited this spot from being saved:</h2>

      <ul>
        <% spot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :latitude, style: "display: block" %>
    <%= form.text_field :latitude %>
  </div>

  <div>
    <%= form.label :longitude, style: "display: block" %>
    <%= form.text_field :longitude %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/spots/_spot.html.erb
<div id="<%= dom_id spot %>">
  <p>
    <strong>Name:</strong>
    <%= spot.name %>
  </p>

  <p>
    <strong>Latitude:</strong>
    <%= spot.latitude %>
  </p>

  <p>
    <strong>Longitude:</strong>
    <%= spot.longitude %>
  </p>

</div>

app/views/spots/edit.html.erb
<h1>Editing spot</h1>

<%= render "form", spot: @spot %>

<br>

<div>
  <%= link_to "Show this spot", @spot %> |
  <%= link_to "Back to spots", spots_path %>
</div>

app/views/spots/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Spots</h1>

<div id="spots">
  <% @spots.each do |spot| %>
    <%= render spot %>
    <p>
      <%= link_to "Show this spot", spot %>
    </p>
  <% end %>
</div>

<%= link_to "New spot", new_spot_path %>

app/views/spots/new.html.erb
<h1>New spot</h1>

<%= render "form", spot: @spot %>

<br>

<div>
  <%= link_to "Back to spots", spots_path %>
</div>

app/views/spots/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @spot %>

<div>
  <%= link_to "Edit this spot", edit_spot_path(@spot) %> |
  <%= link_to "Back to spots", spots_path %>

  <%= button_to "Destroy this spot", @spot, method: :delete %>
</div>