config/routes.rb
Rails.application.routes.draw do
  resources :spots
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'wods', to: "wods#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/explore', to: 'sessions#explore'
  get '/test-route', to: 'pages#test'
  get '/attributions', to: 'pages#attributions'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users#, except: 'index'

  resources :charges
  resources :sessions
  resources :sessions, module: "sessions" do
    resources :charges do
      get :success, to: 'charges#success'
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  #
  scope :recently_created, -> {
    where("created_at >= ?", Date.today - 2.days)
  }
  #
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :charges

  has_one_attached :avatar
  has_many :sessions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]

  def index
    @users = User.all
  end

  def show
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  private
    def set_user
      @user = User.friendly.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :avatar, :biography)
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_avatar.html.erb
<% if user.avatar.attached? %>
  <%= image_tag user.avatar, width: "100%" %>
<% else %>
  <%= image_tag "default_avatar.jpg", width: "100%" %>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group py-1">
    <%= form.label :email %>
    <%= form.text_field :email, class: "form-control" %>
  </div>

  <div class="form-group py-1">
    <%= form.label "User Name" %>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="row py-1">
    <div class="col-2">
      <%= form.label :current %>
      <%= render "users/avatar", user: user %>
    </div>
    <div class="col-10">
      <div class="form-group">
        <%= form.label :avatar %>
        <%= form.file_field :avatar, multiple: false, direct_upload: true, class: "form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group py-1">
    <%= form.label :biography %>
    <%= form.text_area :biography, class: "form-control" %>
  </div>

  <div class="actions">
    <%= form.submit "Save", class: "btn btn-primary my-1 btn-block col-12" %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div class="card my-2">
  <div class="card-body">
    <div class="row">
      <div class="col-lg-2 col-md-6 col-sm-6 col-6 py-3">
        <%= render 'users/avatar', user: user %>
      </div>
      <div class="col-lg-10 col-md-6 col-sm-6 col-6 py-1">
        <% if user.biography %>
          <small class="text-muted"><%= user.biography %></small>
        <% end %>

        <p class="card-text">
          <small class="text-muted">
            <% if user.name %>
              <strong>Username:</strong> <%= user.name %><br>
            <% end %>
            <strong>Member Since:</strong> <%= user.created_at.strftime('%b %Y')  %><br>
          </small>
        </p>
      </div>
    </div>
    <% if buttons %>
      <div class="row">
        <div class="col">
          <%= link_to "Public Profile", user_path(user), class: "btn btn-primary btn-block col-12 my-1" %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="row py-3">
  <div class="<%= common_column_spacing %>">
    <h1>Edit User</h1>

    <%= render 'form', user: @user %>

    <%= link_to 'View Public Profile', @user, class: "btn btn-primary btn-block btn-block col-12 my-1" %>
    <%= link_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to sign out?' }, class: "btn btn-danger btn-block col-12 my-1" %>
    <%= link_to 'Back', users_path, class: "btn btn-primary btn-block btn-block col-12 my-1" %>
  </div>
</div>

app/views/users/index.html.erb
<div class="container">
  <div class="row py-3">
    <div class="<%= common_column_spacing %>">
      <% @users.each_with_index do |user, index| %>
        <%= render 'user', user: user, buttons: true %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<section class="mt-6">
  <div class="container">
    <div class="row">
      <div class="<%= common_column_spacing %>">
        <%= render "user", user: @user, buttons: false %>
        <%= link_to "Get Started", root_path, class: "btn btn-primary col-12" %>
      </div>
    </div>


    <div class="row row-cols-1 row-cols-md-2 row-cols-lg-3 pb-5">
      <% if @user.sessions.count == 0 %>
        <div class="<%= common_column_spacing %> py-3">This user has not yet created photo session.</div>
      <% else %>
        <% @user.sessions.reverse.each do |session| %>
          <div class="col mt-5">
            <div class="card shadow-light hover-lift-light">
              <%= image_tag session.images.sample unless session.images.empty? %>
              <div class="card-body">
                <%= link_to session_path(session), class: "h4 text-dark text-decoration-none" do %>
                  <%= session.title if session.title %>
                <% end %>
                <p>
                  <%= session.created_at.strftime("%B %-d, %Y") %>
                </p>
                <p>
                  Session Photos (<%= session.images.count %>)
                </p>
                <p>
                  <%= session.description if session.description %>
                </p>
                <%= link_to "See More", session_path(session), class: "btn btn-primary col-12" %>
              </div>
            </div>
          </div>
        <% end %>
      <% end %>
    </div>
  </div>
</section>