config/routes.rb
Rails.application.routes.draw do
  resources :spots
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'wods', to: "wods#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/explore', to: 'sessions#explore'
  get '/test-route', to: 'pages#test'
  get '/attributions', to: 'pages#attributions'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users#, except: 'index'

  resources :charges
  resources :sessions
  resources :sessions, module: "sessions" do
    resources :charges do
      get :success, to: 'charges#success'
    end
  end
end

app/models/charge.rb
class Charge < ApplicationRecord
  has_one :asset

  belongs_to :purchaser, class_name: 'User', optional: true 
  belongs_to :seller, class_name: 'User'
  belongs_to :session, optional: true

  monetize :price_cents

  def full_size_asset_storage_url(asset_id)
    ActiveStorage::Attachment.find(asset_id)
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[index, update]

  def index
    @charges_buys = Charge.where(purchaser_id: current_user.id)
    @charges_sales = Charge.where(seller_id: current_user.id)
  end

  def show
  end

  def new
    @charge = Charge.new
  end

  def edit
  end

  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: "Charge was successfully created." }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: "Charge was successfully updated." }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
        format.html { redirect_to charges_url, notice: "We don't delete the charges." }
        format.json { head :no_content }
    end
    # @charge.destroy
    # respond_to do |format|
    #   format.html { redirect_to charges_url, notice: "Charge was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    def set_charge
      @charge = Charge.find(params[:id])
    end

    def charge_params
      params.require(:charge).permit(:success_url, :cancel_url)
    end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/views/charges/_charge.html.erb
<div class="card mb-3">
  <div class="card-body">
    <div class="row">
      <div class="col-lg-5">
        <p><%= charge.session.title %></p>
        <span class="badge rounded-pill bg-success text-end">Payment Successful #<%= charge.id %></span>
      </div>
      <div class="col-lg-5">
        <p>
          Purchaser: 
          <% if charge.purchaser %>
            <%= charge.purchaser.slug %>
          <% else %>
            Unknown user
          <% end %>
        </p>
        <p><%= time_ago_in_words charge.created_at %></p>
      </div>
      <div class="col-lg-2">
        <%= link_to charge do %>
          <%= image_tag ActiveStorage::Attachment.find(charge.asset_id), width: "100%" %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/charges/_charge_list_group_item.html.erb
<li class="list-group-item">
  <div class="row">
    <div class="col">
      <%= image_tag charge.full_size_asset_storage_url(charge.asset_id), width: "100px" %>
    </div>
    <div class="col">
      <%= link_to "Success URL", charge.success_url, class: "btn btn-primary" %>
    </div>
    <div class="col">
      <%= link_to "Success URL", charge.success_url, class: "btn btn-primary" %>
    </div>
    <div class="col">
      <%= link_to 'Show', charge, class: "btn btn-primary" %>
    </div>
  </div>
</li>

app/views/charges/_form.html.erb
<%= form_with(model: charge) do |form| %>
  <% if charge.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(charge.errors.count, "error") %> prohibited this charge from being saved:</h2>

      <ul>
        <% charge.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :success_url %>
    <%= form.text_field :success_url %>
  </div>

  <div class="field">
    <%= form.label :cancel_url %>
    <%= form.text_field :cancel_url %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/charges/edit.html.erb
<h1>Editing Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Show', @charge %> |
<%= link_to 'Back', charges_path %>

app/views/charges/index.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-lg-6 py-3">
    <div class="card">
      <div class="card-header">
        Photos you Have Sold
      </div>
      <ul class="list-group list-group-flush">
        <% @charges_buys.each do |charge| %>
          <%= render 'charges/charge_list_group_item', charge: charge %>
        <% end %>
        <% if @charges_buys.empty? %>
          <li class='list-group-item'>No Sales Yet</li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="col-lg-6 py-3">
    <div class="card">
      <div class="card-header">
        Photos you Have Bought
      </div>
      <ul class="list-group list-group-flush">
        <% @charges_sales.each do |charge| %>
          <%= render 'charges/charge_list_group_item', charge: charge %>
        <% end %>
        <% if @charges_sales.empty? %>
          <li class='list-group-item'>No Sales Yet</li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/charges/new.html.erb
<h1>New Charge</h1>

<%= render 'form', charge: @charge %>

<%= link_to 'Back', charges_path %>

app/views/charges/show.html.erb
<div class="container">
  <div class="row py-3">
    <div class="<%= common_column_spacing %>">
      <div class="card">
        <%= image_tag ActiveStorage::Attachment.find(@charge.asset_id), width: "100%" %>
        <div class="card-body">
          <p>
            <strong>Sale Price in USD Cents:</strong>
            <%= @charge.price_cents %>
          </p>

          <p>
            <strong>Seller Email:</strong>
            <%= @charge.seller.email %>
          </p>

          <p>
            <strong>Purchaser Email:</strong>
            <%= @charge.purchaser.email if @charge.purchaser %>
          </p>

          <%= link_to 'Edit', edit_charge_path(@charge), class: "btn btn-primary btn-block col-12 my-1" %>
          <%= link_to 'Back', root_path, class: "btn btn-success btn-block col-12 my-1" %>
        </div>
      </div>
    </div>
  </div>
</div>