config/routes.rb
Rails.application.routes.draw do
  resources :spots
  get 'errors/not_found'
  get 'errors/internal_server_error'
  get 'wods', to: "wods#index"

  match '/404', to: "errors#not_found", via: :all
  match '/500', to: 'errors#internal_server_error', via: :all

  root to: 'pages#index'

  get '/about', to: 'pages#about'
  get '/explore', to: 'sessions#explore'
  get '/test-route', to: 'pages#test'
  get '/attributions', to: 'pages#attributions'

  devise_for :users do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :users#, except: 'index'

  resources :charges
  resources :sessions
  resources :sessions, module: "sessions" do
    resources :charges do
      get :success, to: 'charges#success'
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/charge.rb
class Charge < ApplicationRecord
  has_one :asset

  belongs_to :purchaser, class_name: 'User', optional: true 
  belongs_to :seller, class_name: 'User'
  belongs_to :session, optional: true

  monetize :price_cents

  def full_size_asset_storage_url(asset_id)
    ActiveStorage::Attachment.find(asset_id)
  end
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
  monetize :default_price_cents
  has_many :charges, dependent: :delete_all

  has_many_attached :images do |attachable|
    attachable.variant :thumb, resize: "400x400"
  end
end

app/models/spot.rb
class Spot < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  #
  scope :recently_created, -> {
    where("created_at >= ?", Date.today - 2.days)
  }
  #
  extend FriendlyId
  friendly_id :name, use: :slugged
  has_many :charges

  has_one_attached :avatar
  has_many :sessions

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  before_action :set_charge, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[index, update]

  def index
    @charges_buys = Charge.where(purchaser_id: current_user.id)
    @charges_sales = Charge.where(seller_id: current_user.id)
  end

  def show
  end

  def new
    @charge = Charge.new
  end

  def edit
  end

  def create
    @charge = Charge.new(charge_params)

    respond_to do |format|
      if @charge.save
        format.html { redirect_to @charge, notice: "Charge was successfully created." }
        format.json { render :show, status: :created, location: @charge }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @charge.update(charge_params)
        format.html { redirect_to @charge, notice: "Charge was successfully updated." }
        format.json { render :show, status: :ok, location: @charge }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @charge.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
        format.html { redirect_to charges_url, notice: "We don't delete the charges." }
        format.json { head :no_content }
    end
    # @charge.destroy
    # respond_to do |format|
    #   format.html { redirect_to charges_url, notice: "Charge was successfully destroyed." }
    #   format.json { head :no_content }
    # end
  end

  private
    def set_charge
      @charge = Charge.find(params[:id])
    end

    def charge_params
      params.require(:charge).permit(:success_url, :cancel_url)
    end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def not_found
    render status: 404
  end

  def internal_server_error
    render status: 500
  end
end

app/controllers/map_controller.rb
class MapController < ApplicationController
  def index
    @surf_spots = Spot.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    if current_user
      @past_sessions = current_user.sessions
      @earnings = Charge.where({seller: current_user, payment_successful: true})
      @purchases = Charge.where({purchaser: current_user})
      @this_months_charge_total = 0
      @earnings.each do |purchase|
        @this_months_charge_total += purchase.price if purchase.payment_successful
      end
      
    else
      @resource_name = :user
      @resource = User.new
      @devise_mapping = Devise.mappings[:user]

      @past_sessions = the_last_10_sessions
    end
    @sessions = the_last_10_sessions
  end

  def about
  end

  def attributions
  end

  def the_last_10_sessions
    Session.limit(10).order(created_at: :desc)
  end
end

app/controllers/spots_controller.rb
class SpotsController < ApplicationController
  before_action :set_spot, only: %i[ show edit update destroy ]

  # GET /spots or /spots.json
  def index
    @spots = Spot.all
  end

  # GET /spots/1 or /spots/1.json
  def show
  end

  # GET /spots/new
  def new
    @spot = Spot.new
  end

  # GET /spots/1/edit
  def edit
  end

  # POST /spots or /spots.json
  def create
    @spot = Spot.new(spot_params)

    respond_to do |format|
      if @spot.save
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully created." }
        format.json { render :show, status: :created, location: @spot }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /spots/1 or /spots/1.json
  def update
    respond_to do |format|
      if @spot.update(spot_params)
        format.html { redirect_to spot_url(@spot), notice: "Spot was successfully updated." }
        format.json { render :show, status: :ok, location: @spot }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @spot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /spots/1 or /spots/1.json
  def destroy
    @spot.destroy

    respond_to do |format|
      format.html { redirect_to spots_url, notice: "Spot was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_spot
      @spot = Spot.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def spot_params
      params.require(:spot).permit(:name, :latitude, :longitude)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:show]

  def index
    @users = User.all
  end

  def show
  end

  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to root_path, notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  private
    def set_user
      @user = User.friendly.find(params[:id])
    end

    def user_params
      params.require(:user).permit(:name, :email, :avatar, :biography)
    end
end

app/controllers/wods_controller.rb
class WodsController < ApplicationController
  def index
    @workouts = load_data
  end

  private

  def load_data
    file_path = Rails.root.join('config', 'workouts.yml')
    YAML.load_file(file_path)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def common_column_spacing
    "col-lg-6 offset-lg-3"
  end

  def format_cents_to_readable price
    (price.to_i/100.0).to_s
  end
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wod_helper.rb
module WodHelper
end

app/views/layouts/_administration.html.erb
<div class="container-fluid mt-4 mt-md-5 mb-7">
  <div class="row">
    <div class="col-lg-3 mb-3">
      <div class="card">
        <div class="card-header" id="admin-page">
          <%= image_tag 'image-hawk-logo.png', width: '40px' %>
          ImageHawk
        </div>
        <div class="list-group list-group-flush" id="list-tab" role="tablist">
          <a class="list-group-item list-group-item-action active" id="list-sessions-list" data-bs-toggle="list" href="#list-sessions" role="tab" aria-controls="list-sessions">Your Sessions</a>
          <a class="list-group-item list-group-item-action" id="list-all-sessions-list" data-bs-toggle="list" href="#list-all-sessions" role="tab" aria-controls="list-all-sessions">All Sessions</a>
          <a class="list-group-item list-group-item-action" id="list-home-list" data-bs-toggle="list" href="#list-home" role="tab" aria-controls="list-home">Earnings</a>
          <a class="list-group-item list-group-item-action" id="list-purchases-list" data-bs-toggle="list" href="#list-purchases" role="tab" aria-controls="list-purchases">Purchases</a>
          <a class="list-group-item list-group-item-action" id="list-settings-list" data-bs-toggle="list" href="#list-settings" role="tab" aria-controls="list-settings">Settings</a>
        </div>
      </div>
      <%= link_to "View Your Public Profile", user_path(current_user), class: "btn btn-primary col-12 my-3", target: "_blank" %>
    </div>

    <div class="col-lg-9 mt-4 mt-lg-0 mb-3">
      <div class="card">
          <div class="tab-content" id="nav-tabContent">

            <div class="tab-pane fade show active" id="list-sessions" role="tabpanel" aria-labelledby="list-sessions-list">
              <div class="card-header">
                Sessions You Have Published
              </div>
              <div class="card-body">
                <%= link_to "Create new session", new_session_path, class: "btn btn-primary col-12 mb-3" %>
                <% @current_user.sessions.reverse.each do |session| %>
                  <%= render session %>
                <% end %>
              </div>
            </div>

            <div class="tab-pane fade" id="list-all-sessions" role="tabpanel" aria-labelledby="list-all-sessions-list">
              <div class="card-header">
                All Sessions
              </div>
              <div class="card-body">
                <% if @sessions.count > 0 %>
                  <% @sessions.reverse.each do |session| %>
                    <%= render session %>
                  <% end %>
                <% else %>
                  <p>You have not created a session yet.</p>
                  <%= link_to "Get Started", new_session_path, class: "btn btn-primary btn-block col-12" %>
                <% end %>
              </div>
            </div>

            <div class="tab-pane fade" id="list-home" role="tabpanel" aria-labelledby="list-home-list">
              <div class="card-header">
                <h6 class="card-header-title text-darkblue">
                  <%= Date.today.last_month.strftime("%B") %> - <%= Date.today.strftime("%B") %> 
                  Earnings ($<%= @this_months_charge_total %>)
                </h6>
              </div>
              <div class="card-body">
                <% if @earnings.count > 0 %>
                  <% @earnings.reverse.each do |charge| %>
                    <%= render charge %>
                  <% end %>
                <% else %>
                  <p>No sales yet.</p>
                <% end %>
              </div>
            </div>

            <div class="tab-pane fade" id="list-purchases" role="tabpanel" aria-labelledby="list-purchases-list">
              <div class="card-header">
                Purchases
              </div>
              <div class="card-body">
                <% if @purchases.count > 0 %>
                  <% @purchases.each do |purchase| %>
                    <%= render purchase %>
                  <% end %>
                <% else %>
                  <p>You have not yet purchased any images.</p>
                <% end %>
              </div>
            </div>

            <div class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">
              <div class="card-header">
                Settings
              </div>
              <div class="card-body">
                <%= render 'users/form', user: current_user %>
                <%= button_to "Sign Out", destroy_user_session_path, method: :delete, data: { confirm: 'Are you sure you want to sign out?' }, class: "btn btn-danger btn-block col-12 my-1" %>
              </div>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_contact_admin_via_whatsapp.html.erb
<div class="py-4">
  <p>If you want to talk about this error with the development team, please contact via WhatsApp</p>
  <%= link_to "Contact on WhatsApp", 'https://wa.me/13476883697', class: "btn btn-success btn-block col-12", target: "_blank" %>
</div>

app/views/layouts/_notifications.html.erb
<div class="container">
  <% if notice %>
    <p class="alert alert-success">
      <%= notice %>
    </p>
  <% end %>
  <% if alert %>
    <p class="alert alert-danger">
      <%= alert %>
    </p>
  <% end %>
</div>

app/views/layouts/_public.html.erb
<div class="container">
  <section class="mt-5 mt-md-7">
    <div class="row align-items-center py-5">
      <div class="col-md-6 pe-lg-5">

        <h1 class="display-4 fw-normal">
          ImageHawk <%= image_tag 'image-hawk-logo.png', width: "40px" %>
        </h1>

        <h2 class="mt-4">
          Sell your surf photography online
        </h2>
      </div>

      <div class="col-md-6 position-relative mt-5 mt-md-0 ps-lg-5">
        <%= render "devise/sessions/login_form", resource: @resource, resource_name: @resource_name, devise_mapping: @devise_mapping %>
        <div class="col-12 d-flex justify-content-center">
        <hr>
        <%= link_to "Create new account", new_user_registration_path, class: "btn btn-success center my-1" %>
        </div>
      </div>
    </div>
  </section>

  <div class="row py-5">
    <div class="col-4 animate-on-scroll">
      <%= image_tag "stranger-page/feature-1.png", width: "100%" %>
    </div>
    <div class="col-4 animate-on-scroll">
      <%= image_tag "stranger-page/feature-2.png", width: "100%" %>
    </div>
    <div class="col-4 animate-on-scroll">
      <%= image_tag "stranger-page/feature-3.png", width: "100%" %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>ImageHawk: Tools to Help You Sell Your Photography and Make More Money as a Photographer</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="A place to sell your photography online. Upload your photography and share low resolution versions for sale to the public.">
    <%= csp_meta_tag %>
    <%= csrf_meta_tags %>

    <link rel="canonical" href="https://www.imagehawk.app/">

    <meta charset="utf-8">    
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <%= favicon_link_tag asset_path('image-hawk-logo-favicon.png') %>
  </head>

  <body class="bg-white">
    <%= render "layouts/notifications" %>
    <%= yield %>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_stranger_content.html.erb
<div class="container">
  <div class="row text-center">
    <div class="col">
      <h1 class="py-3">
        Image Hawk
        <%= image_tag "image-hawk-logo.png", width: '50px' %>
      </h1>
      <p>Image Hawk is a service helps photographers sell photography.</p>
    </div>
  </div>
  <div class="row py-3">
    <div class="col-4">
      <%= link_to "Explore Photos", explore_path, class: "btn btn-primary btn-block col-12" %>
    </div>
    <div class="col-4">
      <%= link_to "Sell Photos", new_user_registration_path, class: "btn btn-primary btn-block col-12" %>
    </div>
    <div class="col-4">
      <%= link_to "Sign In", new_user_session_path, class: "btn btn-primary btn-block col-12" %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<div class="container">
  <div class="row">
    <div class="card">
      <div class="card-body">
        <h1>Image Hawk is a platform for photographers to sell their work.</h1>
        <p>Make money with your action photography work.</p>
        <p>Here's an example of your business:</p>
        <p>You take photos of surfers from the beach.</p>
        <p>The surfers want to buy the high-resolution photos you took.</p>
        <p>When they get out of the water, you give them a card and say, "I got some great photos of you. You can check them out here".</p>
        <p>That card has your ImageHawk address on there.</p>
        <p>Later that day, you upload your work to ImageHawk.</p>
        <p>The surfer can see low resolution images and pick the ones they want. They pay via credit card online and the high-resolution photos are automatically sent to them.</p>
        <p>You get paid via direct deposit, PayPal or it can be converted to Bitcoin and moved to your wallet.</p>

        <h3>Features to Develop</h3>
        <ul>
          <li>Automate payout to photographers</li>
          <li>Create interface for photographers to see successful charges</li>
          <li>Automate Instagram posting so photographers can automatically announce their latest upload</li>
        </ul>
      </div>
    </div>
  </div>
</div>

app/views/pages/attributions.html.erb
<div class="container">
  <div class="row py-5">
    <div class="<%= common_column_spacing %>">
      <p>The following image was downloaded with a Free License, remember to always attribute the author which can be done by adding <%= link_to '“Vecteezy.com”','https://www.vecteezy.com/vector-art/7725079-eye-logo-simple-and-elegant-logo-for-business' %> to your design and linking to vecteezy.com where possible.</p>
      <div class="d-flex justify-content-center">
        <%= link_to 'https://www.vecteezy.com/vector-art/7725079-eye-logo-simple-and-elegant-logo-for-business' do %>
          <%= image_tag 'image-hawk-logo.png', width: "500px" %>
        <% end %>
      </div>
      <%= link_to "Dashboard", root_path, class: "btn btn-primary col-12" %>
    </div>
  </div>
</div>

app/views/pages/index.html.erb
<%= render "layouts/administration" if current_user %>
<%= render 'layouts/public' unless current_user %>